name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate tag
        id: generate-tag
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t lucioschenkel/nlw.journey.api:${{ steps.generate-tag.outputs.tag }} .

      - name: Push image
        run: |
          docker push lucioschenkel/nlw.journey.api:${{ steps.generate-tag.outputs.tag }}
          docker tag lucioschenkel/nlw.journey.api:${{ steps.generate-tag.outputs.tag }} lucioschenkel/nlw.journey.api:latest
          docker push lucioschenkel/nlw.journey.api:latest
